# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0
     
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test
  deploy:
    docker:
      - image: openjdk:9-jre
    working_directory: cf/
    steps:
      - checkout
      - run:
          command: |
            curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
            ./cf api $CF_API
            ./cf auth $CF_USER $CF_PASSWORD
            ./cf target -o $CF_ORG
            ./cf push --random-route
            export TEST_ROUTE=`./cf routes | grep -i reconfubulator | awk '{print $2}'`
            curl -i -H "Accept: application/x-www-form-urlencoded" \
                    -H "Content-Type: application/x-www-form-urlencoded" \
                    -d "text"="@sp1 @sp2 battled @sp4 @sp5 and lost 3:10!" \
                    -X POST \
                    "https://${TEST_ROUTE}.cfapps.eu10.hana.ondemand.com"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
