version: 2
jobs:


  build:
    docker:
      - image: circleci/node:9.8.0
      - image: mongo:3.6.3
        command: [mongod, --smallfiles]
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test && npm run coverage
  
  
  
  smoketest:
    docker:
      - image: openjdk:9-jre
    working_directory: cf/
    environment:
      - NODE_ENV=smoketest
    steps:
      - checkout
      - run:
          name: Install CF CLI
          command: |
            curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
      - run:
          name: CF Push
          command: |
            export APP_NAME=${CIRCLE_PROJECT_REPONAME}-${NODE_ENV}-`echo ${CIRCLE_SHA1} | cut -c -7`
            ./cf api $CF_API
            ./cf auth $CF_USER $CF_PASSWORD
            ./cf target -o $CF_ORG
            ./cf push ${APP_NAME}
      - run:
          name: Smoke Test
          command: |
              export APP_NAME=${CIRCLE_PROJECT_REPONAME}-${NODE_ENV}-`echo ${CIRCLE_SHA1} | cut -c -7`
              curl -i -H "Accept: application/x-www-form-urlencoded" \
                   -H "Content-Type: application/x-www-form-urlencoded" \
                   -d "text=<@W123> <@W456> battled <@W789> <@W012> and lost 3:10!" \
                   -X POST \
                   "https://${APP_NAME}.cfapps.eu10.hana.ondemand.com/slack/result"
      - run:
          name: Logs
          when: on_fail
          command: |
              APP_NAME=${CIRCLE_PROJECT_REPONAME}-${NODE_ENV}-`echo ${CIRCLE_SHA1} | cut -c -7` 
              ./cf logs ${APP_NAME} --recent
      - run:
          name: Clean Up
          when: always
          command: |
              APP_NAME=${CIRCLE_PROJECT_REPONAME}-${NODE_ENV}-`echo ${CIRCLE_SHA1} | cut -c -7` 
              ./cf delete ${APP_NAME} -r -f
  
  
  
  deploy-to-production:
    docker:
      - image: openjdk:9-jre
    working_directory: cf/
    environment:
      - NODE_ENV=production
    steps:
      - checkout
      - run:
          name: Install CF CLI
          command: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
      - run:
          name: CF Push
          command: |
            export APP_NAME=${CIRCLE_PROJECT_REPONAME}
            ./cf api $CF_API
            ./cf auth $CF_USER $CF_PASSWORD
            ./cf target -o $CF_ORG
            ./cf push ${APP_NAME}
      - run:
          name: Logs
          when: on_fail
          command: |
              APP_NAME=${CIRCLE_PROJECT_REPONAME}
              ./cf logs ${APP_NAME} --recent

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - smoketest:
          requires:
            - build
      - deploy-to-production:
          type: approval
          requires:
            - smoketest
            - build
          filters:
            branches:
              only: deployment
